version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/config:/usr/local/etc/redis/redis.conf
      - ./redis/command:/usr/local/etc/command
